//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtimeSender
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", ConfigurationName="RealtimeSender.RealTimeInformationImportFacade")]
    internal interface RealTimeInformationImportFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRealTimeInfoTO))]
        System.Threading.Tasks.Task<RealtimeSender.importDelayInfoResponse> importDelayInfoAsync(RealtimeSender.importDelayInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRealTimeInfoTO))]
        System.Threading.Tasks.Task<RealtimeSender.importRealTimeInfoResponse> importRealTimeInfoAsync(RealtimeSender.importRealTimeInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class DelayInfoTO : AbstractRealTimeInfoTO
    {
        
        private DelayTO[] delaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delays", Order=0)]
        public DelayTO[] delays
        {
            get
            {
                return this.delaysField;
            }
            set
            {
                this.delaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class DelayTO
    {
        
        private int causeField;
        
        private string detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class ValidationErrorTO
    {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class VehicleTO
    {
        
        private string deviceIdField;
        
        private string numberField;
        
        private int positionField;
        
        private bool positionFieldSpecified;
        
        private int orientationField;
        
        private bool orientationFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string deviceId
        {
            get
            {
                return this.deviceIdField;
            }
            set
            {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int orientation
        {
            get
            {
                return this.orientationField;
            }
            set
            {
                this.orientationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orientationSpecified
        {
            get
            {
                return this.orientationFieldSpecified;
            }
            set
            {
                this.orientationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealTimeInfoTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DelayInfoTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class AbstractRealTimeInfoTO
    {
        
        private int eventCodeField;
        
        private string divisionField;
        
        private string stopAreaField;
        
        private long timeStampField;
        
        private int deltaField;
        
        private bool deltaFieldSpecified;
        
        private VehicleTO[] vehiclesField;
        
        private long trainCombinationCompleteField;
        
        private bool trainCombinationCompleteFieldSpecified;
        
        private long tripIdentificationDateField;
        
        private bool tripIdentificationDateFieldSpecified;
        
        private string tripNumberField;
        
        private string tripStartLocationField;
        
        private string trackField;
        
        private string tracksectionField;
        
        private int trackpositionField;
        
        private bool trackpositionFieldSpecified;
        
        private string vehicleNumberField;
        
        private string employeeIdField;
        
        private string deviceIdField;
        
        private string plannedTripNumberField;
        
        private long plannedTripIdentificationDateField;
        
        private bool plannedTripIdentificationDateFieldSpecified;
        
        private string versionField;
        
        private int shuntingTripField;
        
        private bool shuntingTripFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int eventCode
        {
            get
            {
                return this.eventCodeField;
            }
            set
            {
                this.eventCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string division
        {
            get
            {
                return this.divisionField;
            }
            set
            {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string stopArea
        {
            get
            {
                return this.stopAreaField;
            }
            set
            {
                this.stopAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long timeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int delta
        {
            get
            {
                return this.deltaField;
            }
            set
            {
                this.deltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deltaSpecified
        {
            get
            {
                return this.deltaFieldSpecified;
            }
            set
            {
                this.deltaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicles", Order=5)]
        public VehicleTO[] vehicles
        {
            get
            {
                return this.vehiclesField;
            }
            set
            {
                this.vehiclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long trainCombinationComplete
        {
            get
            {
                return this.trainCombinationCompleteField;
            }
            set
            {
                this.trainCombinationCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trainCombinationCompleteSpecified
        {
            get
            {
                return this.trainCombinationCompleteFieldSpecified;
            }
            set
            {
                this.trainCombinationCompleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long tripIdentificationDate
        {
            get
            {
                return this.tripIdentificationDateField;
            }
            set
            {
                this.tripIdentificationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tripIdentificationDateSpecified
        {
            get
            {
                return this.tripIdentificationDateFieldSpecified;
            }
            set
            {
                this.tripIdentificationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string tripNumber
        {
            get
            {
                return this.tripNumberField;
            }
            set
            {
                this.tripNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string tripStartLocation
        {
            get
            {
                return this.tripStartLocationField;
            }
            set
            {
                this.tripStartLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string track
        {
            get
            {
                return this.trackField;
            }
            set
            {
                this.trackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string tracksection
        {
            get
            {
                return this.tracksectionField;
            }
            set
            {
                this.tracksectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int trackposition
        {
            get
            {
                return this.trackpositionField;
            }
            set
            {
                this.trackpositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trackpositionSpecified
        {
            get
            {
                return this.trackpositionFieldSpecified;
            }
            set
            {
                this.trackpositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string vehicleNumber
        {
            get
            {
                return this.vehicleNumberField;
            }
            set
            {
                this.vehicleNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string employeeId
        {
            get
            {
                return this.employeeIdField;
            }
            set
            {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string deviceId
        {
            get
            {
                return this.deviceIdField;
            }
            set
            {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string plannedTripNumber
        {
            get
            {
                return this.plannedTripNumberField;
            }
            set
            {
                this.plannedTripNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public long plannedTripIdentificationDate
        {
            get
            {
                return this.plannedTripIdentificationDateField;
            }
            set
            {
                this.plannedTripIdentificationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plannedTripIdentificationDateSpecified
        {
            get
            {
                return this.plannedTripIdentificationDateFieldSpecified;
            }
            set
            {
                this.plannedTripIdentificationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int shuntingTrip
        {
            get
            {
                return this.shuntingTripField;
            }
            set
            {
                this.shuntingTripField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shuntingTripSpecified
        {
            get
            {
                return this.shuntingTripFieldSpecified;
            }
            set
            {
                this.shuntingTripFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class RealTimeInfoTO : AbstractRealTimeInfoTO
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class importDelayInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("delayInfoTO", IsNullable=false)]
        public RealtimeSender.DelayInfoTO[] importDelayInfo;
        
        public importDelayInfoRequest()
        {
        }
        
        public importDelayInfoRequest(RealtimeSender.DelayInfoTO[] importDelayInfo)
        {
            this.importDelayInfo = importDelayInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class importDelayInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importDelayInfoResponse", Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public RealtimeSender.ValidationErrorTO[] importDelayInfoResponse1;
        
        public importDelayInfoResponse()
        {
        }
        
        public importDelayInfoResponse(RealtimeSender.ValidationErrorTO[] importDelayInfoResponse1)
        {
            this.importDelayInfoResponse1 = importDelayInfoResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class importRealTimeInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("realTimeInfoTO", IsNullable=false)]
        public RealtimeSender.RealTimeInfoTO[] importRealTimeInfo;
        
        public importRealTimeInfoRequest()
        {
        }
        
        public importRealTimeInfoRequest(RealtimeSender.RealTimeInfoTO[] importRealTimeInfo)
        {
            this.importRealTimeInfo = importRealTimeInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class importRealTimeInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importRealTimeInfoResponse", Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public RealtimeSender.ValidationErrorTO[] importRealTimeInfoResponse1;
        
        public importRealTimeInfoResponse()
        {
        }
        
        public importRealTimeInfoResponse(RealtimeSender.ValidationErrorTO[] importRealTimeInfoResponse1)
        {
            this.importRealTimeInfoResponse1 = importRealTimeInfoResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    internal interface RealTimeInformationImportFacadeChannel : RealtimeSender.RealTimeInformationImportFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    internal partial class RealTimeInformationImportFacadeClient : System.ServiceModel.ClientBase<RealtimeSender.RealTimeInformationImportFacade>, RealtimeSender.RealTimeInformationImportFacade
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RealTimeInformationImportFacadeClient() : 
                base(RealTimeInformationImportFacadeClient.GetDefaultBinding(), RealTimeInformationImportFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RealTimeInformationImportFacadePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealTimeInformationImportFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(RealTimeInformationImportFacadeClient.GetBindingForEndpoint(endpointConfiguration), RealTimeInformationImportFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealTimeInformationImportFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RealTimeInformationImportFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealTimeInformationImportFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RealTimeInformationImportFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealTimeInformationImportFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealtimeSender.importDelayInfoResponse> RealtimeSender.RealTimeInformationImportFacade.importDelayInfoAsync(RealtimeSender.importDelayInfoRequest request)
        {
            return base.Channel.importDelayInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealtimeSender.importDelayInfoResponse> importDelayInfoAsync(RealtimeSender.DelayInfoTO[] importDelayInfo)
        {
            RealtimeSender.importDelayInfoRequest inValue = new RealtimeSender.importDelayInfoRequest();
            inValue.importDelayInfo = importDelayInfo;
            return ((RealtimeSender.RealTimeInformationImportFacade)(this)).importDelayInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealtimeSender.importRealTimeInfoResponse> RealtimeSender.RealTimeInformationImportFacade.importRealTimeInfoAsync(RealtimeSender.importRealTimeInfoRequest request)
        {
            return base.Channel.importRealTimeInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealtimeSender.importRealTimeInfoResponse> importRealTimeInfoAsync(RealtimeSender.RealTimeInfoTO[] importRealTimeInfo)
        {
            RealtimeSender.importRealTimeInfoRequest inValue = new RealtimeSender.importRealTimeInfoRequest();
            inValue.importRealTimeInfo = importRealTimeInfo;
            return ((RealtimeSender.RealTimeInformationImportFacade)(this)).importRealTimeInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RealTimeInformationImportFacadePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RealTimeInformationImportFacadePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/de/RealTimeInformationImportFacadeBean");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RealTimeInformationImportFacadeClient.GetBindingForEndpoint(EndpointConfiguration.RealTimeInformationImportFacadePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RealTimeInformationImportFacadeClient.GetEndpointAddress(EndpointConfiguration.RealTimeInformationImportFacadePort);
        }
        
        public enum EndpointConfiguration
        {
            
            RealTimeInformationImportFacadePort,
        }
    }
}
