SET FRAMEWORK=netcoreapp3.1
SET RUNTIME=linux-x64

SET TARGETDIR=.
SET SOURCEDIR=.\bin\Release\%FRAMEWORK%\%RUNTIME%
SET DROPBOXDIR=%USERPROFILE%\Dropbox\Public\EBuEf

SET SERVICENAME=EBuEf2IVUVehicle
SET DEBFILE=%SERVICENAME%.*.*.*.%RUNTIME%.deb

pushd .\%SERVICENAME%\

dotnet restore
dotnet build -c release -f netcoreapp3.1 .\%SERVICENAME%\%SERVICENAME%.csproj 

BASH -c "sh Create_Linux-x64_%SERVICENAME%.sh"

DEL /q %TARGETDIR%\%DEBFILE%
DEL /q %DROPBOXDIR%\%DEBFILE%

XCOPY /y .\EBuEf2IVUCrew\%SOURCEDIR%\%DEBFILE% %TARGETDIR%
XCOPY /y .\EBuEf2IVUCrew\%SOURCEDIR%\%DEBFILE% %DROPBOXDIR%

SET SERVICENAME=EBuEf2IVUCrew
SET DEBFILE=%SERVICENAME%.*.*.*.%RUNTIME%.deb

pushd .\%SERVICENAME%\

dotnet restore
dotnet build -c release -f netcoreapp3.1 .\%SERVICENAME%\%SERVICENAME%.csproj 

BASH -c "sh Create_Linux-x64_%SERVICENAME%.sh"

DEL /q %TARGETDIR%\%DEBFILE%
DEL /q %DROPBOXDIR%\%DEBFILE%

XCOPY /y .\EBuEf2IVUCrew\%SOURCEDIR%\%DEBFILE% %TARGETDIR%
XCOPY /y .\EBuEf2IVUCrew\%SOURCEDIR%\%DEBFILE% %DROPBOXDIR%

popd
pause