SET FRAMEWORK=netcoreapp3.1
SET RUNTIME=linux-x64
REM SET RUNTIME=linux-arm

SET FILENAME=EBuEf2IVUCore.*.*.*.%RUNTIME%.deb
SET SOURCEDIR=.\EBuef2IVUCore\bin\Release\%FRAMEWORK%\%RUNTIME%
SET TARGETDIR=.
SET DROPBOXDIR=%USERPROFILE%\Dropbox\Public\EBuEf

DEL /q %TARGETDIR%\%FILENAME%
DEL /q %DROPBOXDIR%\%FILENAME%

REM pushd .\EBuEf2IVUCore
REM dotnet publish -c Release -r %RUNTIME% -f %FRAMEWORK% --self-contained
REM dotnet deb -c Release -r %RUNTIME% -f %FRAMEWORK%
REM popd

BASH -c "sh Create_Linux-x64.sh"

XCOPY /y %SOURCEDIR%\%FILENAME% %TARGETDIR%
XCOPY /y %SOURCEDIR%\%FILENAME% %DROPBOXDIR%

pause