version: '3.3'

services:
    crew:
        network_mode: host
        volumes:
            - '/mnt/c/Users/mgr/Entwicklung/EBuEf2IVU/Programs/EBuEf2IVUCrew/ebuef2ivucrew-settings.docker.xml:/ebuef2ivucrew-settings.xml'
        command: '-s /ebuef2ivucrew-settings.xml'
        image: ebuef2ivucrew

    path:
        network_mode: host
        volumes:
            - '/mnt/c/Users/mgr/Entwicklung/EBuEf2IVU/Programs/EBuEf2IVUPath/ebuef2ivupath-settings.docker.xml:/ebuef2ivupath-settings.xml'
        command: '-s /ebuef2ivupath-settings.xml'
        image: ebuef2ivupath

    vehicle:
        network_mode: host
        volumes:
            - '/mnt/c/Users/mgr/Entwicklung/EBuEf2IVU/Programs/EBuEf2IVUVehicle/ebuef2ivuvehicle-settings.docker.xml:/ebuef2ivuvehicle-settings.xml'
        command: '-s /ebuef2ivuvehicle-settings.xml'
        image: ebuef2ivuvehicle