//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrewChecker
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService", ConfigurationName="CrewChecker.CrewOnTripPortType")]
    internal interface CrewOnTripPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/CrewOnTripWebService/exportCrewAssignmentsForRoute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CrewChecker.exportCrewAssignmentsForRouteResponse> exportCrewAssignmentsForRouteAsync(CrewChecker.exportCrewAssignmentsForRoute request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/CrewOnTripWebService/exportCrewAssignmentsForTrip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CrewChecker.exportCrewAssignmentsForTripResponse> exportCrewAssignmentsForTripAsync(CrewChecker.exportCrewAssignmentsForTrip request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/CrewOnTripWebService/exportCrewAssignmentsForTrips", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CrewChecker.exportCrewAssignmentsForTripsResponse> exportCrewAssignmentsForTripsAsync(CrewChecker.exportCrewAssignmentsForTrips request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService")]
    public partial class exportCrewAssignmentsForRouteRequest
    {
        
        private string divisionField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private string routeField;
        
        private string planningLevelField;
        
        private bool withPassengersField;
        
        private bool withPassengersFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string division
        {
            get
            {
                return this.divisionField;
            }
            set
            {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string route
        {
            get
            {
                return this.routeField;
            }
            set
            {
                this.routeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string planningLevel
        {
            get
            {
                return this.planningLevelField;
            }
            set
            {
                this.planningLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool withPassengers
        {
            get
            {
                return this.withPassengersField;
            }
            set
            {
                this.withPassengersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withPassengersSpecified
        {
            get
            {
                return this.withPassengersFieldSpecified;
            }
            set
            {
                this.withPassengersFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService")]
    public partial class exportCrewAssignmentsForTripsRequest
    {
        
        private string divisionField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private string[] tripNumbersField;
        
        private string planningLevelField;
        
        private bool withPassengersField;
        
        private bool withPassengersFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string division
        {
            get
            {
                return this.divisionField;
            }
            set
            {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tripNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] tripNumbers
        {
            get
            {
                return this.tripNumbersField;
            }
            set
            {
                this.tripNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string planningLevel
        {
            get
            {
                return this.planningLevelField;
            }
            set
            {
                this.planningLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool withPassengers
        {
            get
            {
                return this.withPassengersField;
            }
            set
            {
                this.withPassengersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withPassengersSpecified
        {
            get
            {
                return this.withPassengersFieldSpecified;
            }
            set
            {
                this.withPassengersFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService")]
    public partial class exportCrewAssignmentsForTripRequest
    {
        
        private string divisionField;
        
        private System.DateTime dateField;
        
        private string tripNumberField;
        
        private string planningLevelField;
        
        private bool withPassengersField;
        
        private bool withPassengersFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string division
        {
            get
            {
                return this.divisionField;
            }
            set
            {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tripNumber
        {
            get
            {
                return this.tripNumberField;
            }
            set
            {
                this.tripNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string planningLevel
        {
            get
            {
                return this.planningLevelField;
            }
            set
            {
                this.planningLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool withPassengers
        {
            get
            {
                return this.withPassengersField;
            }
            set
            {
                this.withPassengersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withPassengersSpecified
        {
            get
            {
                return this.withPassengersFieldSpecified;
            }
            set
            {
                this.withPassengersFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService")]
    public partial class error
    {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService")]
    public partial class phoneNumber
    {
        
        private string typeField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService")]
    public partial class tripAssignment
    {
        
        private System.DateTime dateField;
        
        private System.DateTime plannedDateField;
        
        private bool plannedDateFieldSpecified;
        
        private string tripField;
        
        private string dutyField;
        
        private string surnameField;
        
        private string nameField;
        
        private string personnelNumberField;
        
        private string depotField;
        
        private string divisionField;
        
        private string divisionDescriptionField;
        
        private string dutyCrewTypeField;
        
        private string dutyCrewTypeDescriptionField;
        
        private System.DateTime tripDepartureTimeField;
        
        private string tripDepartureTimezoneField;
        
        private string tripDepartureStationField;
        
        private System.DateTime tripArrivalTimeField;
        
        private string tripArrivalTimezoneField;
        
        private string tripArrivalStationField;
        
        private System.DateTime previousTripDayField;
        
        private bool previousTripDayFieldSpecified;
        
        private string previousTripNumberField;
        
        private System.DateTime previousTripArrivalTimeField;
        
        private bool previousTripArrivalTimeFieldSpecified;
        
        private System.DateTime nextTripDayField;
        
        private bool nextTripDayFieldSpecified;
        
        private string nextTripNumberField;
        
        private System.DateTime nextTripDepartureTimeField;
        
        private bool nextTripDepartureTimeFieldSpecified;
        
        private phoneNumber[] phoneNumberField;
        
        private string employeePersonnelTypeField;
        
        private string employeeOriginField;
        
        private string employeeOriginTimezoneField;
        
        private System.DateTime employeeDepartureTimeField;
        
        private bool employeeDepartureTimeFieldSpecified;
        
        private string employeeDestinationField;
        
        private string employeeDestinationTimezoneField;
        
        private System.DateTime employeeArrivalTimeField;
        
        private bool employeeArrivalTimeFieldSpecified;
        
        private string[] dutyElementCrewTypeField;
        
        private bool isPassengerField;
        
        private bool isPassengerFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime plannedDate
        {
            get
            {
                return this.plannedDateField;
            }
            set
            {
                this.plannedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plannedDateSpecified
        {
            get
            {
                return this.plannedDateFieldSpecified;
            }
            set
            {
                this.plannedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string trip
        {
            get
            {
                return this.tripField;
            }
            set
            {
                this.tripField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string duty
        {
            get
            {
                return this.dutyField;
            }
            set
            {
                this.dutyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string personnelNumber
        {
            get
            {
                return this.personnelNumberField;
            }
            set
            {
                this.personnelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string depot
        {
            get
            {
                return this.depotField;
            }
            set
            {
                this.depotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string division
        {
            get
            {
                return this.divisionField;
            }
            set
            {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string divisionDescription
        {
            get
            {
                return this.divisionDescriptionField;
            }
            set
            {
                this.divisionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string dutyCrewType
        {
            get
            {
                return this.dutyCrewTypeField;
            }
            set
            {
                this.dutyCrewTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string dutyCrewTypeDescription
        {
            get
            {
                return this.dutyCrewTypeDescriptionField;
            }
            set
            {
                this.dutyCrewTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=12)]
        public System.DateTime tripDepartureTime
        {
            get
            {
                return this.tripDepartureTimeField;
            }
            set
            {
                this.tripDepartureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string tripDepartureTimezone
        {
            get
            {
                return this.tripDepartureTimezoneField;
            }
            set
            {
                this.tripDepartureTimezoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string tripDepartureStation
        {
            get
            {
                return this.tripDepartureStationField;
            }
            set
            {
                this.tripDepartureStationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=15)]
        public System.DateTime tripArrivalTime
        {
            get
            {
                return this.tripArrivalTimeField;
            }
            set
            {
                this.tripArrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string tripArrivalTimezone
        {
            get
            {
                return this.tripArrivalTimezoneField;
            }
            set
            {
                this.tripArrivalTimezoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string tripArrivalStation
        {
            get
            {
                return this.tripArrivalStationField;
            }
            set
            {
                this.tripArrivalStationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=18)]
        public System.DateTime previousTripDay
        {
            get
            {
                return this.previousTripDayField;
            }
            set
            {
                this.previousTripDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool previousTripDaySpecified
        {
            get
            {
                return this.previousTripDayFieldSpecified;
            }
            set
            {
                this.previousTripDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string previousTripNumber
        {
            get
            {
                return this.previousTripNumberField;
            }
            set
            {
                this.previousTripNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=20)]
        public System.DateTime previousTripArrivalTime
        {
            get
            {
                return this.previousTripArrivalTimeField;
            }
            set
            {
                this.previousTripArrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool previousTripArrivalTimeSpecified
        {
            get
            {
                return this.previousTripArrivalTimeFieldSpecified;
            }
            set
            {
                this.previousTripArrivalTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=21)]
        public System.DateTime nextTripDay
        {
            get
            {
                return this.nextTripDayField;
            }
            set
            {
                this.nextTripDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nextTripDaySpecified
        {
            get
            {
                return this.nextTripDayFieldSpecified;
            }
            set
            {
                this.nextTripDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string nextTripNumber
        {
            get
            {
                return this.nextTripNumberField;
            }
            set
            {
                this.nextTripNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=23)]
        public System.DateTime nextTripDepartureTime
        {
            get
            {
                return this.nextTripDepartureTimeField;
            }
            set
            {
                this.nextTripDepartureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nextTripDepartureTimeSpecified
        {
            get
            {
                return this.nextTripDepartureTimeFieldSpecified;
            }
            set
            {
                this.nextTripDepartureTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phoneNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public phoneNumber[] phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string employeePersonnelType
        {
            get
            {
                return this.employeePersonnelTypeField;
            }
            set
            {
                this.employeePersonnelTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string employeeOrigin
        {
            get
            {
                return this.employeeOriginField;
            }
            set
            {
                this.employeeOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string employeeOriginTimezone
        {
            get
            {
                return this.employeeOriginTimezoneField;
            }
            set
            {
                this.employeeOriginTimezoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=28)]
        public System.DateTime employeeDepartureTime
        {
            get
            {
                return this.employeeDepartureTimeField;
            }
            set
            {
                this.employeeDepartureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool employeeDepartureTimeSpecified
        {
            get
            {
                return this.employeeDepartureTimeFieldSpecified;
            }
            set
            {
                this.employeeDepartureTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string employeeDestination
        {
            get
            {
                return this.employeeDestinationField;
            }
            set
            {
                this.employeeDestinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string employeeDestinationTimezone
        {
            get
            {
                return this.employeeDestinationTimezoneField;
            }
            set
            {
                this.employeeDestinationTimezoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=31)]
        public System.DateTime employeeArrivalTime
        {
            get
            {
                return this.employeeArrivalTimeField;
            }
            set
            {
                this.employeeArrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool employeeArrivalTimeSpecified
        {
            get
            {
                return this.employeeArrivalTimeFieldSpecified;
            }
            set
            {
                this.employeeArrivalTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dutyElementCrewType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=32)]
        public string[] dutyElementCrewType
        {
            get
            {
                return this.dutyElementCrewTypeField;
            }
            set
            {
                this.dutyElementCrewTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public bool isPassenger
        {
            get
            {
                return this.isPassengerField;
            }
            set
            {
                this.isPassengerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isPassengerSpecified
        {
            get
            {
                return this.isPassengerFieldSpecified;
            }
            set
            {
                this.isPassengerFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService")]
    public partial class exportCrewAssignmentsResponse
    {
        
        private tripAssignment[] tripAssignmentField;
        
        private error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tripAssignment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public tripAssignment[] tripAssignment
        {
            get
            {
                return this.tripAssignmentField;
            }
            set
            {
                this.tripAssignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class exportCrewAssignmentsForRoute
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService", Order=0)]
        public CrewChecker.exportCrewAssignmentsForRouteRequest exportCrewAssignmentsForRouteRequest;
        
        public exportCrewAssignmentsForRoute()
        {
        }
        
        public exportCrewAssignmentsForRoute(CrewChecker.exportCrewAssignmentsForRouteRequest exportCrewAssignmentsForRouteRequest)
        {
            this.exportCrewAssignmentsForRouteRequest = exportCrewAssignmentsForRouteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class exportCrewAssignmentsForRouteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService", Order=0)]
        public CrewChecker.exportCrewAssignmentsResponse exportCrewAssignmentsResponse;
        
        public exportCrewAssignmentsForRouteResponse()
        {
        }
        
        public exportCrewAssignmentsForRouteResponse(CrewChecker.exportCrewAssignmentsResponse exportCrewAssignmentsResponse)
        {
            this.exportCrewAssignmentsResponse = exportCrewAssignmentsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class exportCrewAssignmentsForTrip
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService", Order=0)]
        public CrewChecker.exportCrewAssignmentsForTripRequest exportCrewAssignmentsForTripRequest;
        
        public exportCrewAssignmentsForTrip()
        {
        }
        
        public exportCrewAssignmentsForTrip(CrewChecker.exportCrewAssignmentsForTripRequest exportCrewAssignmentsForTripRequest)
        {
            this.exportCrewAssignmentsForTripRequest = exportCrewAssignmentsForTripRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class exportCrewAssignmentsForTripResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService", Order=0)]
        public CrewChecker.exportCrewAssignmentsResponse exportCrewAssignmentsResponse;
        
        public exportCrewAssignmentsForTripResponse()
        {
        }
        
        public exportCrewAssignmentsForTripResponse(CrewChecker.exportCrewAssignmentsResponse exportCrewAssignmentsResponse)
        {
            this.exportCrewAssignmentsResponse = exportCrewAssignmentsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class exportCrewAssignmentsForTrips
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService", Order=0)]
        public CrewChecker.exportCrewAssignmentsForTripsRequest exportCrewAssignmentsForTripsRequest;
        
        public exportCrewAssignmentsForTrips()
        {
        }
        
        public exportCrewAssignmentsForTrips(CrewChecker.exportCrewAssignmentsForTripsRequest exportCrewAssignmentsForTripsRequest)
        {
            this.exportCrewAssignmentsForTripsRequest = exportCrewAssignmentsForTripsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class exportCrewAssignmentsForTripsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/CrewOnTripWebService", Order=0)]
        public CrewChecker.exportCrewAssignmentsResponse exportCrewAssignmentsResponse;
        
        public exportCrewAssignmentsForTripsResponse()
        {
        }
        
        public exportCrewAssignmentsForTripsResponse(CrewChecker.exportCrewAssignmentsResponse exportCrewAssignmentsResponse)
        {
            this.exportCrewAssignmentsResponse = exportCrewAssignmentsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface CrewOnTripPortTypeChannel : CrewChecker.CrewOnTripPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class CrewOnTripPortTypeClient : System.ServiceModel.ClientBase<CrewChecker.CrewOnTripPortType>, CrewChecker.CrewOnTripPortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrewOnTripPortTypeClient() : 
                base(CrewOnTripPortTypeClient.GetDefaultBinding(), CrewOnTripPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CrewOnTripWebFacadeBeanPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrewOnTripPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(CrewOnTripPortTypeClient.GetBindingForEndpoint(endpointConfiguration), CrewOnTripPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrewOnTripPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrewOnTripPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrewOnTripPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrewOnTripPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrewOnTripPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewChecker.exportCrewAssignmentsForRouteResponse> CrewChecker.CrewOnTripPortType.exportCrewAssignmentsForRouteAsync(CrewChecker.exportCrewAssignmentsForRoute request)
        {
            return base.Channel.exportCrewAssignmentsForRouteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewChecker.exportCrewAssignmentsForRouteResponse> exportCrewAssignmentsForRouteAsync(CrewChecker.exportCrewAssignmentsForRouteRequest exportCrewAssignmentsForRouteRequest)
        {
            CrewChecker.exportCrewAssignmentsForRoute inValue = new CrewChecker.exportCrewAssignmentsForRoute();
            inValue.exportCrewAssignmentsForRouteRequest = exportCrewAssignmentsForRouteRequest;
            return ((CrewChecker.CrewOnTripPortType)(this)).exportCrewAssignmentsForRouteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewChecker.exportCrewAssignmentsForTripResponse> CrewChecker.CrewOnTripPortType.exportCrewAssignmentsForTripAsync(CrewChecker.exportCrewAssignmentsForTrip request)
        {
            return base.Channel.exportCrewAssignmentsForTripAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewChecker.exportCrewAssignmentsForTripResponse> exportCrewAssignmentsForTripAsync(CrewChecker.exportCrewAssignmentsForTripRequest exportCrewAssignmentsForTripRequest)
        {
            CrewChecker.exportCrewAssignmentsForTrip inValue = new CrewChecker.exportCrewAssignmentsForTrip();
            inValue.exportCrewAssignmentsForTripRequest = exportCrewAssignmentsForTripRequest;
            return ((CrewChecker.CrewOnTripPortType)(this)).exportCrewAssignmentsForTripAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewChecker.exportCrewAssignmentsForTripsResponse> CrewChecker.CrewOnTripPortType.exportCrewAssignmentsForTripsAsync(CrewChecker.exportCrewAssignmentsForTrips request)
        {
            return base.Channel.exportCrewAssignmentsForTripsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewChecker.exportCrewAssignmentsForTripsResponse> exportCrewAssignmentsForTripsAsync(CrewChecker.exportCrewAssignmentsForTripsRequest exportCrewAssignmentsForTripsRequest)
        {
            CrewChecker.exportCrewAssignmentsForTrips inValue = new CrewChecker.exportCrewAssignmentsForTrips();
            inValue.exportCrewAssignmentsForTripsRequest = exportCrewAssignmentsForTripsRequest;
            return ((CrewChecker.CrewOnTripPortType)(this)).exportCrewAssignmentsForTripsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CrewOnTripWebFacadeBeanPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CrewOnTripWebFacadeBeanPort))
            {
                return new System.ServiceModel.EndpointAddress("http://bnb18327.ivu-ag.com:20000/intf.crewontrip.impl/CrewOnTripWebFacadeBean");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CrewOnTripPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.CrewOnTripWebFacadeBeanPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CrewOnTripPortTypeClient.GetEndpointAddress(EndpointConfiguration.CrewOnTripWebFacadeBeanPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CrewOnTripWebFacadeBeanPort,
        }
    }
}
