//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainPathImportService110
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TechnicalFaultResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathImportResponse
    {
        
        private int protocolTransactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int protocolTransactionId
        {
            get
            {
                return this.protocolTransactionIdField;
            }
            set
            {
                this.protocolTransactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TimetableVersion
    {
        
        private string abbreviationField;
        
        private DateInterval validityField;
        
        private string idField;
        
        /// <remarks/>
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        public DateInterval validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class DateInterval
    {
        
        private System.DateTime beginField;
        
        private System.DateTime endField;
        
        private string bitmaskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime begin
        {
            get
            {
                return this.beginField;
            }
            set
            {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public string bitmask
        {
            get
            {
                return this.bitmaskField;
            }
            set
            {
                this.bitmaskField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class NetworkPointKey
    {
        
        private string abbreviationField;
        
        private string externalNumberField;
        
        private string primaryLocationCodeField;
        
        private StopType stopTypeField;
        
        private string idField;
        
        /// <remarks/>
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string externalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }
        
        /// <remarks/>
        public string primaryLocationCode
        {
            get
            {
                return this.primaryLocationCodeField;
            }
            set
            {
                this.primaryLocationCodeField = value;
            }
        }
        
        /// <remarks/>
        public StopType stopType
        {
            get
            {
                return this.stopTypeField;
            }
            set
            {
                this.stopTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public enum StopType
    {
        
        /// <remarks/>
        STOP_POST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TafTapTsiAttributes
    {
        
        private string referenceTrainIdCoreField;
        
        private string trainIdCoreField;
        
        private string trainIdVariantField;
        
        private string routeIdCoreField;
        
        private string routeIdVariantField;
        
        private string pathRequestIdCoreField;
        
        private string pathRequestIdVariantField;
        
        private string pathIdCoreField;
        
        private string pathIdVariantField;
        
        private ProcessType processTypeField;
        
        private bool processTypeFieldSpecified;
        
        private bool waiveAcceptanceField;
        
        private bool waiveAcceptanceFieldSpecified;
        
        private string contactInfoNameField;
        
        private string contactInfoAddressField;
        
        private string contactInfoPhoneNumberField;
        
        private string contactInfoFaxNumberField;
        
        private string contactInfoEmailField;
        
        private string contactInfoFreeTextFieldField;
        
        private string freeTextFieldField;
        
        /// <remarks/>
        public string referenceTrainIdCore
        {
            get
            {
                return this.referenceTrainIdCoreField;
            }
            set
            {
                this.referenceTrainIdCoreField = value;
            }
        }
        
        /// <remarks/>
        public string trainIdCore
        {
            get
            {
                return this.trainIdCoreField;
            }
            set
            {
                this.trainIdCoreField = value;
            }
        }
        
        /// <remarks/>
        public string trainIdVariant
        {
            get
            {
                return this.trainIdVariantField;
            }
            set
            {
                this.trainIdVariantField = value;
            }
        }
        
        /// <remarks/>
        public string routeIdCore
        {
            get
            {
                return this.routeIdCoreField;
            }
            set
            {
                this.routeIdCoreField = value;
            }
        }
        
        /// <remarks/>
        public string routeIdVariant
        {
            get
            {
                return this.routeIdVariantField;
            }
            set
            {
                this.routeIdVariantField = value;
            }
        }
        
        /// <remarks/>
        public string pathRequestIdCore
        {
            get
            {
                return this.pathRequestIdCoreField;
            }
            set
            {
                this.pathRequestIdCoreField = value;
            }
        }
        
        /// <remarks/>
        public string pathRequestIdVariant
        {
            get
            {
                return this.pathRequestIdVariantField;
            }
            set
            {
                this.pathRequestIdVariantField = value;
            }
        }
        
        /// <remarks/>
        public string pathIdCore
        {
            get
            {
                return this.pathIdCoreField;
            }
            set
            {
                this.pathIdCoreField = value;
            }
        }
        
        /// <remarks/>
        public string pathIdVariant
        {
            get
            {
                return this.pathIdVariantField;
            }
            set
            {
                this.pathIdVariantField = value;
            }
        }
        
        /// <remarks/>
        public ProcessType processType
        {
            get
            {
                return this.processTypeField;
            }
            set
            {
                this.processTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool processTypeSpecified
        {
            get
            {
                return this.processTypeFieldSpecified;
            }
            set
            {
                this.processTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool waiveAcceptance
        {
            get
            {
                return this.waiveAcceptanceField;
            }
            set
            {
                this.waiveAcceptanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool waiveAcceptanceSpecified
        {
            get
            {
                return this.waiveAcceptanceFieldSpecified;
            }
            set
            {
                this.waiveAcceptanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string contactInfoName
        {
            get
            {
                return this.contactInfoNameField;
            }
            set
            {
                this.contactInfoNameField = value;
            }
        }
        
        /// <remarks/>
        public string contactInfoAddress
        {
            get
            {
                return this.contactInfoAddressField;
            }
            set
            {
                this.contactInfoAddressField = value;
            }
        }
        
        /// <remarks/>
        public string contactInfoPhoneNumber
        {
            get
            {
                return this.contactInfoPhoneNumberField;
            }
            set
            {
                this.contactInfoPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string contactInfoFaxNumber
        {
            get
            {
                return this.contactInfoFaxNumberField;
            }
            set
            {
                this.contactInfoFaxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string contactInfoEmail
        {
            get
            {
                return this.contactInfoEmailField;
            }
            set
            {
                this.contactInfoEmailField = value;
            }
        }
        
        /// <remarks/>
        public string contactInfoFreeTextField
        {
            get
            {
                return this.contactInfoFreeTextFieldField;
            }
            set
            {
                this.contactInfoFreeTextFieldField = value;
            }
        }
        
        /// <remarks/>
        public string freeTextField
        {
            get
            {
                return this.freeTextFieldField;
            }
            set
            {
                this.freeTextFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public enum ProcessType
    {
        
        /// <remarks/>
        NEW_PATH_REQUEST_ANNUAL_TIMETABLE,
        
        /// <remarks/>
        LATE_PATH_REQUEST_ANNUAL_TIMETABLE,
        
        /// <remarks/>
        SHORT_TERM_PATH_REQUEST,
        
        /// <remarks/>
        ROLLING_PLANNING_PATH_REQUEST,
        
        /// <remarks/>
        FEASIBILITY_STUDY,
        
        /// <remarks/>
        PATH_MODIFICATION_BY_RU,
        
        /// <remarks/>
        PATH_ALTERATION_BY_IM,
        
        /// <remarks/>
        PRE_ARRANGED_PATH_PUBLISHED_BY_RFC,
        
        /// <remarks/>
        CATALOGUE_PATH_PUBLISHED_BY_IM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainItinerarySegmentAttributes
    {
        
        private string responsibleApplicantField;
        
        private string responsibleRUField;
        
        private string responsibleIMField;
        
        /// <remarks/>
        public string responsibleApplicant
        {
            get
            {
                return this.responsibleApplicantField;
            }
            set
            {
                this.responsibleApplicantField = value;
            }
        }
        
        /// <remarks/>
        public string responsibleRU
        {
            get
            {
                return this.responsibleRUField;
            }
            set
            {
                this.responsibleRUField = value;
            }
        }
        
        /// <remarks/>
        public string responsibleIM
        {
            get
            {
                return this.responsibleIMField;
            }
            set
            {
                this.responsibleIMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainStop
    {
        
        private TrainStopStopPoint stopPointField;
        
        private bool handoverField;
        
        private bool handoverFieldSpecified;
        
        private bool interchangeField;
        
        private bool interchangeFieldSpecified;
        
        private TrainItinerarySegmentAttributes itinerarySegmentAttributesField;
        
        /// <remarks/>
        public TrainStopStopPoint stopPoint
        {
            get
            {
                return this.stopPointField;
            }
            set
            {
                this.stopPointField = value;
            }
        }
        
        /// <remarks/>
        public bool handover
        {
            get
            {
                return this.handoverField;
            }
            set
            {
                this.handoverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool handoverSpecified
        {
            get
            {
                return this.handoverFieldSpecified;
            }
            set
            {
                this.handoverFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool interchange
        {
            get
            {
                return this.interchangeField;
            }
            set
            {
                this.interchangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool interchangeSpecified
        {
            get
            {
                return this.interchangeFieldSpecified;
            }
            set
            {
                this.interchangeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TrainItinerarySegmentAttributes itinerarySegmentAttributes
        {
            get
            {
                return this.itinerarySegmentAttributesField;
            }
            set
            {
                this.itinerarySegmentAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainStopStopPoint
    {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class Times
    {
        
        private System.DateTime commercialArrivalTimeField;
        
        private bool commercialArrivalTimeFieldSpecified;
        
        private int commercialArrivalDayOffsetField;
        
        private bool commercialArrivalDayOffsetFieldSpecified;
        
        private System.DateTime commercialDepartureTimeField;
        
        private bool commercialDepartureTimeFieldSpecified;
        
        private int commercialDepartureDayOffsetField;
        
        private bool commercialDepartureDayOffsetFieldSpecified;
        
        private System.DateTime operationalArrivalTimeField;
        
        private bool operationalArrivalTimeFieldSpecified;
        
        private int operationalArrivalDayOffsetField;
        
        private bool operationalArrivalDayOffsetFieldSpecified;
        
        private System.DateTime operationalDepartureTimeField;
        
        private bool operationalDepartureTimeFieldSpecified;
        
        private int operationalDepartureDayOffsetField;
        
        private bool operationalDepartureDayOffsetFieldSpecified;
        
        private string operationalWaitDurationField;
        
        private string operationalStopDurationField;

        [System.Xml.Serialization.XmlElementAttribute("commercialArrivalTime")]
        public string commercialArrivalTimeText
        {
            get
            {
                return this.commercialArrivalTimeField.ToString("HH:mm:ss");
            }
            set { }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        [System.Xml.Serialization.XmlIgnore]
        public System.DateTime commercialArrivalTime
        {
            get
            {
                return this.commercialArrivalTimeField;
            }
            set
            {
                this.commercialArrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commercialArrivalTimeTextSpecified
        {
            get
            {
                return this.commercialArrivalTimeFieldSpecified;
            }
            set
            {
                this.commercialArrivalTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int commercialArrivalDayOffset
        {
            get
            {
                return this.commercialArrivalDayOffsetField;
            }
            set
            {
                this.commercialArrivalDayOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commercialArrivalDayOffsetSpecified
        {
            get
            {
                return this.commercialArrivalDayOffsetFieldSpecified;
            }
            set
            {
                this.commercialArrivalDayOffsetFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("commercialDepartureTime")]
        public string commercialDepartureTimeText
        {
            get
            {
                return this.commercialDepartureTimeField.ToString("HH:mm:ss");
            }
            set { }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        [System.Xml.Serialization.XmlIgnore]
        public System.DateTime commercialDepartureTime
        {
            get
            {
                return this.commercialDepartureTimeField;
            }
            set
            {
                this.commercialDepartureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commercialDepartureTimeTextSpecified
        {
            get
            {
                return this.commercialDepartureTimeFieldSpecified;
            }
            set
            {
                this.commercialDepartureTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int commercialDepartureDayOffset
        {
            get
            {
                return this.commercialDepartureDayOffsetField;
            }
            set
            {
                this.commercialDepartureDayOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commercialDepartureDayOffsetSpecified
        {
            get
            {
                return this.commercialDepartureDayOffsetFieldSpecified;
            }
            set
            {
                this.commercialDepartureDayOffsetFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("operationalArrivalTime")]
        public string operationalArrivalTimeText
        {
            get
            {
                return this.operationalArrivalTimeField.ToString("HH:mm:ss");
            }
            set { }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        [System.Xml.Serialization.XmlIgnore]
        public System.DateTime operationalArrivalTime
        {
            get
            {
                return this.operationalArrivalTimeField;
            }
            set
            {
                this.operationalArrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationalArrivalTimeTextSpecified
        {
            get
            {
                return this.operationalArrivalTimeFieldSpecified;
            }
            set
            {
                this.operationalArrivalTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int operationalArrivalDayOffset
        {
            get
            {
                return this.operationalArrivalDayOffsetField;
            }
            set
            {
                this.operationalArrivalDayOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationalArrivalDayOffsetSpecified
        {
            get
            {
                return this.operationalArrivalDayOffsetFieldSpecified;
            }
            set
            {
                this.operationalArrivalDayOffsetFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("operationalDepartureTime")]
        public string operationalDepartureTimeText
        {
            get
            {
                return this.operationalDepartureTimeField.ToString("HH:mm:ss");
            }
            set { }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        [System.Xml.Serialization.XmlIgnore]
        public System.DateTime operationalDepartureTime
        {
            get
            {
                return this.operationalDepartureTimeField;
            }
            set
            {
                this.operationalDepartureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationalDepartureTimeTextSpecified
        {
            get
            {
                return this.operationalDepartureTimeFieldSpecified;
            }
            set
            {
                this.operationalDepartureTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int operationalDepartureDayOffset
        {
            get
            {
                return this.operationalDepartureDayOffsetField;
            }
            set
            {
                this.operationalDepartureDayOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationalDepartureDayOffsetSpecified
        {
            get
            {
                return this.operationalDepartureDayOffsetFieldSpecified;
            }
            set
            {
                this.operationalDepartureDayOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string operationalWaitDuration
        {
            get
            {
                return this.operationalWaitDurationField;
            }
            set
            {
                this.operationalWaitDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string operationalStopDuration
        {
            get
            {
                return this.operationalStopDurationField;
            }
            set
            {
                this.operationalStopDurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class SystemAttribute
    {
        
        private string keyField;
        
        private string[] valuesField;
        
        /// <remarks/>
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class AttributeKey
    {
        
        private string nameField;
        
        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class Attribute
    {
        
        private AttributeKey attributeKeyField;
        
        private AttributeAttributeValue attributeValueField;
        
        /// <remarks/>
        public AttributeKey attributeKey
        {
            get
            {
                return this.attributeKeyField;
            }
            set
            {
                this.attributeKeyField = value;
            }
        }
        
        /// <remarks/>
        public AttributeAttributeValue attributeValue
        {
            get
            {
                return this.attributeValueField;
            }
            set
            {
                this.attributeValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class AttributeAttributeValue
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("booleanValue", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("decimalValue", typeof(double), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("numericValue", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("stringValue", typeof(string), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class VehicleType
    {
        
        private string vehicleTypeField;
        
        private int maximumLengthField;
        
        private bool maximumLengthFieldSpecified;
        
        private int maximumWeightField;
        
        private bool maximumWeightFieldSpecified;
        
        private string trainModelSeriesField;
        
        private TractionRole tractionRoleField;
        
        private bool tractionRoleFieldSpecified;
        
        private string tractionPositionField;
        
        private Attribute[] attributesField;
        
        /// <remarks/>
        public string vehicleType
        {
            get
            {
                return this.vehicleTypeField;
            }
            set
            {
                this.vehicleTypeField = value;
            }
        }
        
        /// <remarks/>
        public int maximumLength
        {
            get
            {
                return this.maximumLengthField;
            }
            set
            {
                this.maximumLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumLengthSpecified
        {
            get
            {
                return this.maximumLengthFieldSpecified;
            }
            set
            {
                this.maximumLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int maximumWeight
        {
            get
            {
                return this.maximumWeightField;
            }
            set
            {
                this.maximumWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumWeightSpecified
        {
            get
            {
                return this.maximumWeightFieldSpecified;
            }
            set
            {
                this.maximumWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string trainModelSeries
        {
            get
            {
                return this.trainModelSeriesField;
            }
            set
            {
                this.trainModelSeriesField = value;
            }
        }
        
        /// <remarks/>
        public TractionRole tractionRole
        {
            get
            {
                return this.tractionRoleField;
            }
            set
            {
                this.tractionRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tractionRoleSpecified
        {
            get
            {
                return this.tractionRoleFieldSpecified;
            }
            set
            {
                this.tractionRoleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tractionPosition
        {
            get
            {
                return this.tractionPositionField;
            }
            set
            {
                this.tractionPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
        public Attribute[] attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public enum TractionRole
    {
        
        /// <remarks/>
        TRAIN_TRACTION,
        
        /// <remarks/>
        INTERMEDIATE_TRACTION,
        
        /// <remarks/>
        BANKING_LOCOMOTIVE,
        
        /// <remarks/>
        BANKING_LOCOMOTIVE_NOT_COUPLED,
        
        /// <remarks/>
        NO_LEADING_ENGINE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class FormationRestriction
    {
        
        private VehicleType[] vehicleTypesField;
        
        private int maximumLengthField;
        
        private bool maximumLengthFieldSpecified;
        
        private int maximumWeightField;
        
        private bool maximumWeightFieldSpecified;
        
        private int minimumMaxSpeedField;
        
        private bool minimumMaxSpeedFieldSpecified;
        
        private int numberOfWaggonsField;
        
        private bool numberOfWaggonsFieldSpecified;
        
        private bool isDefaultField;
        
        private bool isDefaultFieldSpecified;
        
        private bool emergencyBrakeOverrideField;
        
        private bool emergencyBrakeOverrideFieldSpecified;
        
        private string etcsLevelField;
        
        private bool lzbField;
        
        private bool lzbFieldSpecified;
        
        private BrakingSystem brakingSystemField;
        
        private bool brakingSystemFieldSpecified;
        
        private TiltingTrainConf tiltingTrainConfField;
        
        private bool tiltingTrainConfFieldSpecified;
        
        private string minBrakingPercentField;
        
        private string lineCategoryField;
        
        private int lengthOfSetOfCarriagesField;
        
        private bool lengthOfSetOfCarriagesFieldSpecified;
        
        private int weightOfSetOfCarriagesField;
        
        private bool weightOfSetOfCarriagesFieldSpecified;
        
        private int maximumSpeedField;
        
        private bool maximumSpeedFieldSpecified;
        
        private double maxAxleWeightField;
        
        private bool maxAxleWeightFieldSpecified;
        
        private string brakingPercentField;
        
        private string tafTapBrakeTypeField;
        
        private string[] tafTapTrainCCSystemsField;
        
        private string tafTapTrainRadioSystemField;
        
        private SystemAttribute[] systemAttributesField;
        
        private Attribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("vehicleType", IsNullable=false)]
        public VehicleType[] vehicleTypes
        {
            get
            {
                return this.vehicleTypesField;
            }
            set
            {
                this.vehicleTypesField = value;
            }
        }
        
        /// <remarks/>
        public int maximumLength
        {
            get
            {
                return this.maximumLengthField;
            }
            set
            {
                this.maximumLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumLengthSpecified
        {
            get
            {
                return this.maximumLengthFieldSpecified;
            }
            set
            {
                this.maximumLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int maximumWeight
        {
            get
            {
                return this.maximumWeightField;
            }
            set
            {
                this.maximumWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumWeightSpecified
        {
            get
            {
                return this.maximumWeightFieldSpecified;
            }
            set
            {
                this.maximumWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int minimumMaxSpeed
        {
            get
            {
                return this.minimumMaxSpeedField;
            }
            set
            {
                this.minimumMaxSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minimumMaxSpeedSpecified
        {
            get
            {
                return this.minimumMaxSpeedFieldSpecified;
            }
            set
            {
                this.minimumMaxSpeedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int numberOfWaggons
        {
            get
            {
                return this.numberOfWaggonsField;
            }
            set
            {
                this.numberOfWaggonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberOfWaggonsSpecified
        {
            get
            {
                return this.numberOfWaggonsFieldSpecified;
            }
            set
            {
                this.numberOfWaggonsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isDefault
        {
            get
            {
                return this.isDefaultField;
            }
            set
            {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isDefaultSpecified
        {
            get
            {
                return this.isDefaultFieldSpecified;
            }
            set
            {
                this.isDefaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool emergencyBrakeOverride
        {
            get
            {
                return this.emergencyBrakeOverrideField;
            }
            set
            {
                this.emergencyBrakeOverrideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emergencyBrakeOverrideSpecified
        {
            get
            {
                return this.emergencyBrakeOverrideFieldSpecified;
            }
            set
            {
                this.emergencyBrakeOverrideFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string etcsLevel
        {
            get
            {
                return this.etcsLevelField;
            }
            set
            {
                this.etcsLevelField = value;
            }
        }
        
        /// <remarks/>
        public bool lzb
        {
            get
            {
                return this.lzbField;
            }
            set
            {
                this.lzbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lzbSpecified
        {
            get
            {
                return this.lzbFieldSpecified;
            }
            set
            {
                this.lzbFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public BrakingSystem brakingSystem
        {
            get
            {
                return this.brakingSystemField;
            }
            set
            {
                this.brakingSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool brakingSystemSpecified
        {
            get
            {
                return this.brakingSystemFieldSpecified;
            }
            set
            {
                this.brakingSystemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TiltingTrainConf tiltingTrainConf
        {
            get
            {
                return this.tiltingTrainConfField;
            }
            set
            {
                this.tiltingTrainConfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tiltingTrainConfSpecified
        {
            get
            {
                return this.tiltingTrainConfFieldSpecified;
            }
            set
            {
                this.tiltingTrainConfFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string minBrakingPercent
        {
            get
            {
                return this.minBrakingPercentField;
            }
            set
            {
                this.minBrakingPercentField = value;
            }
        }
        
        /// <remarks/>
        public string lineCategory
        {
            get
            {
                return this.lineCategoryField;
            }
            set
            {
                this.lineCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int lengthOfSetOfCarriages
        {
            get
            {
                return this.lengthOfSetOfCarriagesField;
            }
            set
            {
                this.lengthOfSetOfCarriagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthOfSetOfCarriagesSpecified
        {
            get
            {
                return this.lengthOfSetOfCarriagesFieldSpecified;
            }
            set
            {
                this.lengthOfSetOfCarriagesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int weightOfSetOfCarriages
        {
            get
            {
                return this.weightOfSetOfCarriagesField;
            }
            set
            {
                this.weightOfSetOfCarriagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightOfSetOfCarriagesSpecified
        {
            get
            {
                return this.weightOfSetOfCarriagesFieldSpecified;
            }
            set
            {
                this.weightOfSetOfCarriagesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int maximumSpeed
        {
            get
            {
                return this.maximumSpeedField;
            }
            set
            {
                this.maximumSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumSpeedSpecified
        {
            get
            {
                return this.maximumSpeedFieldSpecified;
            }
            set
            {
                this.maximumSpeedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double maxAxleWeight
        {
            get
            {
                return this.maxAxleWeightField;
            }
            set
            {
                this.maxAxleWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxAxleWeightSpecified
        {
            get
            {
                return this.maxAxleWeightFieldSpecified;
            }
            set
            {
                this.maxAxleWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string brakingPercent
        {
            get
            {
                return this.brakingPercentField;
            }
            set
            {
                this.brakingPercentField = value;
            }
        }
        
        /// <remarks/>
        public string tafTapBrakeType
        {
            get
            {
                return this.tafTapBrakeTypeField;
            }
            set
            {
                this.tafTapBrakeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("tafTapTrainCCSystem", IsNullable=false)]
        public string[] tafTapTrainCCSystems
        {
            get
            {
                return this.tafTapTrainCCSystemsField;
            }
            set
            {
                this.tafTapTrainCCSystemsField = value;
            }
        }
        
        /// <remarks/>
        public string tafTapTrainRadioSystem
        {
            get
            {
                return this.tafTapTrainRadioSystemField;
            }
            set
            {
                this.tafTapTrainRadioSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("systemAttribute", IsNullable=false)]
        public SystemAttribute[] systemAttributes
        {
            get
            {
                return this.systemAttributesField;
            }
            set
            {
                this.systemAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
        public Attribute[] attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public enum BrakingSystem
    {
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        P2,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        RMg,
        
        /// <remarks/>
        RWb,
        
        /// <remarks/>
        PMg,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public enum TiltingTrainConf
    {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        active,
        
        /// <remarks/>
        passive,
        
        /// <remarks/>
        lateral,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class ItinerarySegmentAttributes
    {
        
        private string trainNumberField;
        
        private string replacementTrainNumberField;
        
        private string[] commercialTrainNamesField;
        
        private string trainProductField;
        
        private FormationRestriction[] formationRestrictionsField;
        
        private string costCenterField;
        
        private string executingCostCenterField;
        
        private string responsibleRUField;
        
        private string tafTapTrainTypeField;
        
        private string tafTapTrafficTypeField;
        
        private SystemAttribute[] systemAttributesField;
        
        private Attribute[] attributesField;
        
        /// <remarks/>
        public string trainNumber
        {
            get
            {
                return this.trainNumberField;
            }
            set
            {
                this.trainNumberField = value;
            }
        }
        
        /// <remarks/>
        public string replacementTrainNumber
        {
            get
            {
                return this.replacementTrainNumberField;
            }
            set
            {
                this.replacementTrainNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("commercialTrainName", IsNullable=false)]
        public string[] commercialTrainNames
        {
            get
            {
                return this.commercialTrainNamesField;
            }
            set
            {
                this.commercialTrainNamesField = value;
            }
        }
        
        /// <remarks/>
        public string trainProduct
        {
            get
            {
                return this.trainProductField;
            }
            set
            {
                this.trainProductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("formationRestriction", IsNullable=false)]
        public FormationRestriction[] formationRestrictions
        {
            get
            {
                return this.formationRestrictionsField;
            }
            set
            {
                this.formationRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public string costCenter
        {
            get
            {
                return this.costCenterField;
            }
            set
            {
                this.costCenterField = value;
            }
        }
        
        /// <remarks/>
        public string executingCostCenter
        {
            get
            {
                return this.executingCostCenterField;
            }
            set
            {
                this.executingCostCenterField = value;
            }
        }
        
        /// <remarks/>
        public string responsibleRU
        {
            get
            {
                return this.responsibleRUField;
            }
            set
            {
                this.responsibleRUField = value;
            }
        }
        
        /// <remarks/>
        public string tafTapTrainType
        {
            get
            {
                return this.tafTapTrainTypeField;
            }
            set
            {
                this.tafTapTrainTypeField = value;
            }
        }
        
        /// <remarks/>
        public string tafTapTrafficType
        {
            get
            {
                return this.tafTapTrafficTypeField;
            }
            set
            {
                this.tafTapTrafficTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("systemAttribute", IsNullable=false)]
        public SystemAttribute[] systemAttributes
        {
            get
            {
                return this.systemAttributesField;
            }
            set
            {
                this.systemAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
        public Attribute[] attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathStop
    {
        
        private ItinerarySegmentAttributes itinerarySegmentAttributesField;
        
        private string[] stoppingReasonsField;
        
        private Times timesField;
        
        private string arrivalTrackField;
        
        private string departureTrackField;
        
        private string linkToNextStopDescriptionField;
        
        private string varyingLinkLengthField;
        
        private TrainPathStopStopPoint stopPointField;
        
        private bool runningField;
        
        private bool runningFieldSpecified;
        
        private SystemAttribute[] systemAttributesField;
        
        private Attribute[] attributesField;
        
        /// <remarks/>
        public ItinerarySegmentAttributes itinerarySegmentAttributes
        {
            get
            {
                return this.itinerarySegmentAttributesField;
            }
            set
            {
                this.itinerarySegmentAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("stoppingReason", IsNullable=false)]
        public string[] stoppingReasons
        {
            get
            {
                return this.stoppingReasonsField;
            }
            set
            {
                this.stoppingReasonsField = value;
            }
        }
        
        /// <remarks/>
        public Times times
        {
            get
            {
                return this.timesField;
            }
            set
            {
                this.timesField = value;
            }
        }
        
        /// <remarks/>
        public string arrivalTrack
        {
            get
            {
                return this.arrivalTrackField;
            }
            set
            {
                this.arrivalTrackField = value;
            }
        }
        
        /// <remarks/>
        public string departureTrack
        {
            get
            {
                return this.departureTrackField;
            }
            set
            {
                this.departureTrackField = value;
            }
        }
        
        /// <remarks/>
        public string linkToNextStopDescription
        {
            get
            {
                return this.linkToNextStopDescriptionField;
            }
            set
            {
                this.linkToNextStopDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string varyingLinkLength
        {
            get
            {
                return this.varyingLinkLengthField;
            }
            set
            {
                this.varyingLinkLengthField = value;
            }
        }
        
        /// <remarks/>
        public TrainPathStopStopPoint stopPoint
        {
            get
            {
                return this.stopPointField;
            }
            set
            {
                this.stopPointField = value;
            }
        }
        
        /// <remarks/>
        public bool running
        {
            get
            {
                return this.runningField;
            }
            set
            {
                this.runningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool runningSpecified
        {
            get
            {
                return this.runningFieldSpecified;
            }
            set
            {
                this.runningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("systemAttribute", IsNullable=false)]
        public SystemAttribute[] systemAttributes
        {
            get
            {
                return this.systemAttributesField;
            }
            set
            {
                this.systemAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
        public Attribute[] attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathStopStopPoint
    {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathVariant
    {
        
        private DateInterval[] validityField;
        
        private string trainDescriptionField;
        
        private string routeNumberField;
        
        private State stateField;
        
        private string createdUserIdField;
        
        private string orderingTransportationCompanyField;
        
        private TrainPathStop[] trainPathItineraryField;
        
        private TrainStop[] trainItineraryField;
        
        private int trainToPathDayShiftField;
        
        private bool trainToPathDayShiftFieldSpecified;
        
        private bool stopsMissingField;
        
        private bool stopsMissingFieldSpecified;
        
        private string leadRUField;
        
        private TafTapTsiAttributes tafTapTsiAttributesField;
        
        private Attribute[] attributesField;
        
        private SystemAttribute[] systemAttributesField;
        
        private string eventKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("validitySegment", IsNullable=false)]
        public DateInterval[] validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
        
        /// <remarks/>
        public string trainDescription
        {
            get
            {
                return this.trainDescriptionField;
            }
            set
            {
                this.trainDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string routeNumber
        {
            get
            {
                return this.routeNumberField;
            }
            set
            {
                this.routeNumberField = value;
            }
        }
        
        /// <remarks/>
        public State state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string createdUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string orderingTransportationCompany
        {
            get
            {
                return this.orderingTransportationCompanyField;
            }
            set
            {
                this.orderingTransportationCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trainPathStop", IsNullable=false)]
        public TrainPathStop[] trainPathItinerary
        {
            get
            {
                return this.trainPathItineraryField;
            }
            set
            {
                this.trainPathItineraryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trainStop", IsNullable=false)]
        public TrainStop[] trainItinerary
        {
            get
            {
                return this.trainItineraryField;
            }
            set
            {
                this.trainItineraryField = value;
            }
        }
        
        /// <remarks/>
        public int trainToPathDayShift
        {
            get
            {
                return this.trainToPathDayShiftField;
            }
            set
            {
                this.trainToPathDayShiftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trainToPathDayShiftSpecified
        {
            get
            {
                return this.trainToPathDayShiftFieldSpecified;
            }
            set
            {
                this.trainToPathDayShiftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool stopsMissing
        {
            get
            {
                return this.stopsMissingField;
            }
            set
            {
                this.stopsMissingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stopsMissingSpecified
        {
            get
            {
                return this.stopsMissingFieldSpecified;
            }
            set
            {
                this.stopsMissingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string leadRU
        {
            get
            {
                return this.leadRUField;
            }
            set
            {
                this.leadRUField = value;
            }
        }
        
        /// <remarks/>
        public TafTapTsiAttributes tafTapTsiAttributes
        {
            get
            {
                return this.tafTapTsiAttributesField;
            }
            set
            {
                this.tafTapTsiAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
        public Attribute[] attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("systemAttribute", IsNullable=false)]
        public SystemAttribute[] systemAttributes
        {
            get
            {
                return this.systemAttributesField;
            }
            set
            {
                this.systemAttributesField = value;
            }
        }
        
        /// <remarks/>
        public string eventKey
        {
            get
            {
                return this.eventKeyField;
            }
            set
            {
                this.eventKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public enum State
    {
        
        /// <remarks/>
        CREATED,
        
        /// <remarks/>
        REQUESTED,
        
        /// <remarks/>
        PROPOSED,
        
        /// <remarks/>
        CONFIRMED,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        REJECTED,
        
        /// <remarks/>
        ALTERED,
        
        /// <remarks/>
        CHANGED,
        
        /// <remarks/>
        MODIFIED,
        
        /// <remarks/>
        PROPOSEDMOD,
        
        /// <remarks/>
        ACCEPTED,
        
        /// <remarks/>
        ACCEPTEDALTERATION,
        
        /// <remarks/>
        DISCARDED,
        
        /// <remarks/>
        REQUESTWITHDRAWN,
        
        /// <remarks/>
        CREATEDEXTERNALLY,
        
        /// <remarks/>
        EDITEDORDER,
        
        /// <remarks/>
        OBJECTED,
        
        /// <remarks/>
        EDITEDMODIFICATION,
        
        /// <remarks/>
        OBJECTEDTOPROPOSEDMOD,
        
        /// <remarks/>
        PROPOSEDPROVISIONALTIMETABLE,
        
        /// <remarks/>
        PROPOSEDFINALTIMETABLE,
        
        /// <remarks/>
        ACCEPTEDPROPOSEDMOD,
        
        /// <remarks/>
        CANCELLATIONSENT,
        
        /// <remarks/>
        REJECTEDALTERATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathKey
    {
        
        private string infrastructureManagerField;
        
        private string trainPathIdField;
        
        private TrainPathKeyTimetableVersion timetableVersionField;
        
        /// <remarks/>
        public string infrastructureManager
        {
            get
            {
                return this.infrastructureManagerField;
            }
            set
            {
                this.infrastructureManagerField = value;
            }
        }
        
        /// <remarks/>
        public string trainPathId
        {
            get
            {
                return this.trainPathIdField;
            }
            set
            {
                this.trainPathIdField = value;
            }
        }
        
        /// <remarks/>
        public TrainPathKeyTimetableVersion timetableVersion
        {
            get
            {
                return this.timetableVersionField;
            }
            set
            {
                this.timetableVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathKeyTimetableVersion
    {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPath
    {
        
        private TrainPathKey trainPathKeyField;
        
        private string infrastructureManagerTrainPathIdField;
        
        private string coordinatingIMField;
        
        private DateInterval[] importValidityFrameField;
        
        private TrainPathVariant[] trainPathVariantsField;
        
        /// <remarks/>
        public TrainPathKey trainPathKey
        {
            get
            {
                return this.trainPathKeyField;
            }
            set
            {
                this.trainPathKeyField = value;
            }
        }
        
        /// <remarks/>
        public string infrastructureManagerTrainPathId
        {
            get
            {
                return this.infrastructureManagerTrainPathIdField;
            }
            set
            {
                this.infrastructureManagerTrainPathIdField = value;
            }
        }
        
        /// <remarks/>
        public string coordinatingIM
        {
            get
            {
                return this.coordinatingIMField;
            }
            set
            {
                this.coordinatingIMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("validitySegment", IsNullable=false)]
        public DateInterval[] importValidityFrame
        {
            get
            {
                return this.importValidityFrameField;
            }
            set
            {
                this.importValidityFrameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trainPathVariant", IsNullable=false)]
        public TrainPathVariant[] trainPathVariants
        {
            get
            {
                return this.trainPathVariantsField;
            }
            set
            {
                this.trainPathVariantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathImportRequest
    {
        
        private string importProfileField;
        
        private TrainPath[] trainPathsField;
        
        private NetworkPointKey[] stopPointsField;
        
        private TimetableVersion[] timetableVersionsField;
        
        /// <remarks/>
        public string importProfile
        {
            get
            {
                return this.importProfileField;
            }
            set
            {
                this.importProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trainPath", IsNullable=false)]
        public TrainPath[] trainPaths
        {
            get
            {
                return this.trainPathsField;
            }
            set
            {
                this.trainPathsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("stopPoint", IsNullable=false)]
        public NetworkPointKey[] stopPoints
        {
            get
            {
                return this.stopPointsField;
            }
            set
            {
                this.stopPointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("timetableVersion", IsNullable=false)]
        public TimetableVersion[] timetableVersions
        {
            get
            {
                return this.timetableVersionsField;
            }
            set
            {
                this.timetableVersionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote", ConfigurationName="ServiceReference1.TrainPathImportWebFacade")]
    public interface TrainPathImportWebFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/mb/intf/trainpath/standard/remote", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrainPathImportService110.TechnicalFaultResponse), Action="http://www.ivu.de/mb/intf/trainpath/standard/remote", Name="technicalFaultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainPathImportService110.importTrainPathsResponse> importTrainPathsAsync(TrainPathImportService110.importTrainPathsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importTrainPathsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote", Order=0)]
        public TrainPathImportService110.TrainPathImportRequest trainPathImportRequest;
        
        public importTrainPathsRequest()
        {
        }
        
        public importTrainPathsRequest(TrainPathImportService110.TrainPathImportRequest trainPathImportRequest)
        {
            this.trainPathImportRequest = trainPathImportRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importTrainPathsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote", Order=0)]
        public TrainPathImportService110.TrainPathImportResponse trainPathImportResponse;
        
        public importTrainPathsResponse()
        {
        }
        
        public importTrainPathsResponse(TrainPathImportService110.TrainPathImportResponse trainPathImportResponse)
        {
            this.trainPathImportResponse = trainPathImportResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface TrainPathImportWebFacadeChannel : TrainPathImportService110.TrainPathImportWebFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class TrainPathImportWebFacadeClient : System.ServiceModel.ClientBase<TrainPathImportService110.TrainPathImportWebFacade>, TrainPathImportService110.TrainPathImportWebFacade
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TrainPathImportWebFacadeClient() : 
                base(TrainPathImportWebFacadeClient.GetDefaultBinding(), TrainPathImportWebFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TrainPathImportWebFacadePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainPathImportWebFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(TrainPathImportWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), TrainPathImportWebFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainPathImportWebFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TrainPathImportWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainPathImportWebFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TrainPathImportWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainPathImportWebFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainPathImportService110.importTrainPathsResponse> TrainPathImportService110.TrainPathImportWebFacade.importTrainPathsAsync(TrainPathImportService110.importTrainPathsRequest request)
        {
            return base.Channel.importTrainPathsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainPathImportService110.importTrainPathsResponse> importTrainPathsAsync(TrainPathImportService110.TrainPathImportRequest trainPathImportRequest)
        {
            TrainPathImportService110.importTrainPathsRequest inValue = new TrainPathImportService110.importTrainPathsRequest();
            inValue.trainPathImportRequest = trainPathImportRequest;
            return ((TrainPathImportService110.TrainPathImportWebFacade)(this)).importTrainPathsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TrainPathImportWebFacadePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TrainPathImportWebFacadePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TrainPathImportWebFacadeClient.GetBindingForEndpoint(EndpointConfiguration.TrainPathImportWebFacadePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TrainPathImportWebFacadeClient.GetEndpointAddress(EndpointConfiguration.TrainPathImportWebFacadePort);
        }
        
        public enum EndpointConfiguration
        {
            
            TrainPathImportWebFacadePort,
        }
    }
}
