//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtimeSender21
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", ConfigurationName="RealtimeSender21.RealTimeInformationImportFacade")]
    internal interface RealTimeInformationImportFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRealTimeInfoTO))]
        System.Threading.Tasks.Task<RealtimeSender21.importRealTimeInfoResponse> importRealTimeInfoAsync(RealtimeSender21.importRealTimeInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRealTimeInfoTO))]
        System.Threading.Tasks.Task<RealtimeSender21.periodicTaskResponse1> periodicTaskAsync(RealtimeSender21.periodicTask1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class RealTimeInfoTO : AbstractRealTimeInfoTO
    {
        
        private DetailTO[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("details", IsNullable=true, Order=0)]
        public DetailTO[] details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class DetailTO
    {
        
        private string causeField;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class periodicTaskResponse
    {
        
        private string outputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string output
        {
            get
            {
                return this.outputField;
            }
            set
            {
                this.outputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class periodicTask
    {
        
        private string inputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string input
        {
            get
            {
                return this.inputField;
            }
            set
            {
                this.inputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class ValidationErrorTO
    {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class VehicleCompositionTO
    {
        
        private string nameField;
        
        private int positionInTrainField;
        
        private bool positionInTrainFieldSpecified;
        
        private VehicleTO leadingVehicleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int positionInTrain
        {
            get
            {
                return this.positionInTrainField;
            }
            set
            {
                this.positionInTrainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionInTrainSpecified
        {
            get
            {
                return this.positionInTrainFieldSpecified;
            }
            set
            {
                this.positionInTrainFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public VehicleTO leadingVehicle
        {
            get
            {
                return this.leadingVehicleField;
            }
            set
            {
                this.leadingVehicleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class VehicleTO
    {
        
        private string deviceIdField;
        
        private string numberField;
        
        private int positionField;
        
        private bool positionFieldSpecified;
        
        private int orientationField;
        
        private bool orientationFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string deviceId
        {
            get
            {
                return this.deviceIdField;
            }
            set
            {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int orientation
        {
            get
            {
                return this.orientationField;
            }
            set
            {
                this.orientationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orientationSpecified
        {
            get
            {
                return this.orientationFieldSpecified;
            }
            set
            {
                this.orientationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealTimeInfoTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws")]
    public partial class AbstractRealTimeInfoTO
    {
        
        private int eventCodeField;
        
        private string divisionField;
        
        private string stopAreaField;
        
        private string gateField;
        
        private string directionField;
        
        private long timeStampField;
        
        private int deltaField;
        
        private bool deltaFieldSpecified;
        
        private VehicleTO[] vehiclesField;
        
        private VehicleCompositionTO[] vehicleCompositionsField;
        
        private long trainCombinationCompleteField;
        
        private bool trainCombinationCompleteFieldSpecified;
        
        private long tripIdentificationDateField;
        
        private bool tripIdentificationDateFieldSpecified;
        
        private string tripNumberField;
        
        private string tripStartLocationField;
        
        private string trackField;
        
        private string tracksectionField;
        
        private int trackpositionField;
        
        private bool trackpositionFieldSpecified;
        
        private string vehicleNumberField;
        
        private string employeeIdField;
        
        private string deviceIdField;
        
        private string plannedTripNumberField;
        
        private long plannedTripIdentificationDateField;
        
        private bool plannedTripIdentificationDateFieldSpecified;
        
        private string versionField;
        
        private int shuntingTripField;
        
        private bool shuntingTripFieldSpecified;
        
        private int classifierField;
        
        private bool classifierFieldSpecified;
        
        private string nextStopAreaField;
        
        private int distanceToStopAreaField;
        
        private bool distanceToStopAreaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int eventCode
        {
            get
            {
                return this.eventCodeField;
            }
            set
            {
                this.eventCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string division
        {
            get
            {
                return this.divisionField;
            }
            set
            {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string stopArea
        {
            get
            {
                return this.stopAreaField;
            }
            set
            {
                this.stopAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string gate
        {
            get
            {
                return this.gateField;
            }
            set
            {
                this.gateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long timeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int delta
        {
            get
            {
                return this.deltaField;
            }
            set
            {
                this.deltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deltaSpecified
        {
            get
            {
                return this.deltaFieldSpecified;
            }
            set
            {
                this.deltaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicles", IsNullable=true, Order=7)]
        public VehicleTO[] vehicles
        {
            get
            {
                return this.vehiclesField;
            }
            set
            {
                this.vehiclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vehicleComposition")]
        public VehicleCompositionTO[] vehicleCompositions
        {
            get
            {
                return this.vehicleCompositionsField;
            }
            set
            {
                this.vehicleCompositionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long trainCombinationComplete
        {
            get
            {
                return this.trainCombinationCompleteField;
            }
            set
            {
                this.trainCombinationCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trainCombinationCompleteSpecified
        {
            get
            {
                return this.trainCombinationCompleteFieldSpecified;
            }
            set
            {
                this.trainCombinationCompleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long tripIdentificationDate
        {
            get
            {
                return this.tripIdentificationDateField;
            }
            set
            {
                this.tripIdentificationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tripIdentificationDateSpecified
        {
            get
            {
                return this.tripIdentificationDateFieldSpecified;
            }
            set
            {
                this.tripIdentificationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string tripNumber
        {
            get
            {
                return this.tripNumberField;
            }
            set
            {
                this.tripNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string tripStartLocation
        {
            get
            {
                return this.tripStartLocationField;
            }
            set
            {
                this.tripStartLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string track
        {
            get
            {
                return this.trackField;
            }
            set
            {
                this.trackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string tracksection
        {
            get
            {
                return this.tracksectionField;
            }
            set
            {
                this.tracksectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int trackposition
        {
            get
            {
                return this.trackpositionField;
            }
            set
            {
                this.trackpositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trackpositionSpecified
        {
            get
            {
                return this.trackpositionFieldSpecified;
            }
            set
            {
                this.trackpositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string vehicleNumber
        {
            get
            {
                return this.vehicleNumberField;
            }
            set
            {
                this.vehicleNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string employeeId
        {
            get
            {
                return this.employeeIdField;
            }
            set
            {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string deviceId
        {
            get
            {
                return this.deviceIdField;
            }
            set
            {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string plannedTripNumber
        {
            get
            {
                return this.plannedTripNumberField;
            }
            set
            {
                this.plannedTripNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public long plannedTripIdentificationDate
        {
            get
            {
                return this.plannedTripIdentificationDateField;
            }
            set
            {
                this.plannedTripIdentificationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plannedTripIdentificationDateSpecified
        {
            get
            {
                return this.plannedTripIdentificationDateFieldSpecified;
            }
            set
            {
                this.plannedTripIdentificationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int shuntingTrip
        {
            get
            {
                return this.shuntingTripField;
            }
            set
            {
                this.shuntingTripField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shuntingTripSpecified
        {
            get
            {
                return this.shuntingTripFieldSpecified;
            }
            set
            {
                this.shuntingTripFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int classifier
        {
            get
            {
                return this.classifierField;
            }
            set
            {
                this.classifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classifierSpecified
        {
            get
            {
                return this.classifierFieldSpecified;
            }
            set
            {
                this.classifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string nextStopArea
        {
            get
            {
                return this.nextStopAreaField;
            }
            set
            {
                this.nextStopAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int distanceToStopArea
        {
            get
            {
                return this.distanceToStopAreaField;
            }
            set
            {
                this.distanceToStopAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distanceToStopAreaSpecified
        {
            get
            {
                return this.distanceToStopAreaFieldSpecified;
            }
            set
            {
                this.distanceToStopAreaFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class importRealTimeInfo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importRealTimeInfo", Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("realTimeInfoTO")]
        public RealtimeSender21.RealTimeInfoTO[] importRealTimeInfo1;
        
        public importRealTimeInfo()
        {
        }
        
        public importRealTimeInfo(RealtimeSender21.RealTimeInfoTO[] importRealTimeInfo1)
        {
            this.importRealTimeInfo1 = importRealTimeInfo1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class importRealTimeInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importRealTimeInfoResponse", Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result")]
        public RealtimeSender21.ValidationErrorTO[] importRealTimeInfoResponse1;
        
        public importRealTimeInfoResponse()
        {
        }
        
        public importRealTimeInfoResponse(RealtimeSender21.ValidationErrorTO[] importRealTimeInfoResponse1)
        {
            this.importRealTimeInfoResponse1 = importRealTimeInfoResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class periodicTask1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", Order=0)]
        public RealtimeSender21.periodicTask periodicTask;
        
        public periodicTask1()
        {
        }
        
        public periodicTask1(RealtimeSender21.periodicTask periodicTask)
        {
            this.periodicTask = periodicTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class periodicTaskResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.facade.ejb.fzd.mb.ivu.de/jaws", Order=0)]
        public RealtimeSender21.periodicTaskResponse periodicTaskResponse;
        
        public periodicTaskResponse1()
        {
        }
        
        public periodicTaskResponse1(RealtimeSender21.periodicTaskResponse periodicTaskResponse)
        {
            this.periodicTaskResponse = periodicTaskResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal interface RealTimeInformationImportFacadeChannel : RealtimeSender21.RealTimeInformationImportFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal partial class RealTimeInformationImportFacadeClient : System.ServiceModel.ClientBase<RealtimeSender21.RealTimeInformationImportFacade>, RealtimeSender21.RealTimeInformationImportFacade
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RealTimeInformationImportFacadeClient() : 
                base(RealTimeInformationImportFacadeClient.GetDefaultBinding(), RealTimeInformationImportFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RealtimeImportWebFacadeBeanPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealTimeInformationImportFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(RealTimeInformationImportFacadeClient.GetBindingForEndpoint(endpointConfiguration), RealTimeInformationImportFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealTimeInformationImportFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RealTimeInformationImportFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealTimeInformationImportFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RealTimeInformationImportFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealTimeInformationImportFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealtimeSender21.importRealTimeInfoResponse> RealtimeSender21.RealTimeInformationImportFacade.importRealTimeInfoAsync(RealtimeSender21.importRealTimeInfo request)
        {
            return base.Channel.importRealTimeInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealtimeSender21.importRealTimeInfoResponse> importRealTimeInfoAsync(RealtimeSender21.RealTimeInfoTO[] importRealTimeInfo1)
        {
            RealtimeSender21.importRealTimeInfo inValue = new RealtimeSender21.importRealTimeInfo();
            inValue.importRealTimeInfo1 = importRealTimeInfo1;
            return ((RealtimeSender21.RealTimeInformationImportFacade)(this)).importRealTimeInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealtimeSender21.periodicTaskResponse1> RealtimeSender21.RealTimeInformationImportFacade.periodicTaskAsync(RealtimeSender21.periodicTask1 request)
        {
            return base.Channel.periodicTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealtimeSender21.periodicTaskResponse1> periodicTaskAsync(RealtimeSender21.periodicTask periodicTask)
        {
            RealtimeSender21.periodicTask1 inValue = new RealtimeSender21.periodicTask1();
            inValue.periodicTask = periodicTask;
            return ((RealtimeSender21.RealTimeInformationImportFacade)(this)).periodicTaskAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RealtimeImportWebFacadeBeanPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RealtimeImportWebFacadeBeanPort))
            {
                return new System.ServiceModel.EndpointAddress("http://bnb22010.ivu-ag.com:20020/intf.realtime.standardimport.impl/RealtimeImport" +
                        "WebFacadeBean");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RealTimeInformationImportFacadeClient.GetBindingForEndpoint(EndpointConfiguration.RealtimeImportWebFacadeBeanPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RealTimeInformationImportFacadeClient.GetEndpointAddress(EndpointConfiguration.RealtimeImportWebFacadeBeanPort);
        }
        
        public enum EndpointConfiguration
        {
            
            RealtimeImportWebFacadeBeanPort,
        }
    }
}
