//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainPathImportService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TechnicalFaultResponse
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathImportResponse
    {
        
        private int protocolTransactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int protocolTransactionId
        {
            get
            {
                return this.protocolTransactionIdField;
            }
            set
            {
                this.protocolTransactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TimetableVersion
    {
        
        private string abbreviationField;
        
        private DateInterval validityField;
        
        private string idField;
        
        /// <remarks/>
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        public DateInterval validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class DateInterval
    {
        
        private System.DateTime beginField;
        
        private System.DateTime endField;
        
        private string bitmaskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime begin
        {
            get
            {
                return this.beginField;
            }
            set
            {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        public string bitmask
        {
            get
            {
                return this.bitmaskField;
            }
            set
            {
                this.bitmaskField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class NetworkPointKey
    {
        
        private string abbreviationField;
        
        private string externalNumberField;
        
        private string stopTypeField;
        
        private string idField;
        
        /// <remarks/>
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string externalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }
        
        /// <remarks/>
        public string stopType
        {
            get
            {
                return this.stopTypeField;
            }
            set
            {
                this.stopTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class Times
    {
        
        private System.DateTime commercialArrivalTimeField;
        
        private bool commercialArrivalTimeFieldSpecified;
        
        private int commercialArrivalDayOffsetField;
        
        private bool commercialArrivalDayOffsetFieldSpecified;
        
        private System.DateTime commercialDepartureTimeField;
        
        private bool commercialDepartureTimeFieldSpecified;
        
        private int commercialDepartureDayOffsetField;
        
        private bool commercialDepartureDayOffsetFieldSpecified;
        
        private System.DateTime operationalArrivalTimeField;
        
        private bool operationalArrivalTimeFieldSpecified;
        
        private int operationalArrivalDayOffsetField;
        
        private bool operationalArrivalDayOffsetFieldSpecified;
        
        private System.DateTime operationalDepartureTimeField;
        
        private bool operationalDepartureTimeFieldSpecified;
        
        private int operationalDepartureDayOffsetField;
        
        private bool operationalDepartureDayOffsetFieldSpecified;
        
        private string operationalWaitDurationField;
        
        private string operationalStopDurationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime commercialArrivalTime
        {
            get
            {
                return this.commercialArrivalTimeField;
            }
            set
            {
                this.commercialArrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commercialArrivalTimeSpecified
        {
            get
            {
                return this.commercialArrivalTimeFieldSpecified;
            }
            set
            {
                this.commercialArrivalTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int commercialArrivalDayOffset
        {
            get
            {
                return this.commercialArrivalDayOffsetField;
            }
            set
            {
                this.commercialArrivalDayOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commercialArrivalDayOffsetSpecified
        {
            get
            {
                return this.commercialArrivalDayOffsetFieldSpecified;
            }
            set
            {
                this.commercialArrivalDayOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime commercialDepartureTime
        {
            get
            {
                return this.commercialDepartureTimeField;
            }
            set
            {
                this.commercialDepartureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commercialDepartureTimeSpecified
        {
            get
            {
                return this.commercialDepartureTimeFieldSpecified;
            }
            set
            {
                this.commercialDepartureTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int commercialDepartureDayOffset
        {
            get
            {
                return this.commercialDepartureDayOffsetField;
            }
            set
            {
                this.commercialDepartureDayOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commercialDepartureDayOffsetSpecified
        {
            get
            {
                return this.commercialDepartureDayOffsetFieldSpecified;
            }
            set
            {
                this.commercialDepartureDayOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime operationalArrivalTime
        {
            get
            {
                return this.operationalArrivalTimeField;
            }
            set
            {
                this.operationalArrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationalArrivalTimeSpecified
        {
            get
            {
                return this.operationalArrivalTimeFieldSpecified;
            }
            set
            {
                this.operationalArrivalTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int operationalArrivalDayOffset
        {
            get
            {
                return this.operationalArrivalDayOffsetField;
            }
            set
            {
                this.operationalArrivalDayOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationalArrivalDayOffsetSpecified
        {
            get
            {
                return this.operationalArrivalDayOffsetFieldSpecified;
            }
            set
            {
                this.operationalArrivalDayOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime operationalDepartureTime
        {
            get
            {
                return this.operationalDepartureTimeField;
            }
            set
            {
                this.operationalDepartureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationalDepartureTimeSpecified
        {
            get
            {
                return this.operationalDepartureTimeFieldSpecified;
            }
            set
            {
                this.operationalDepartureTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int operationalDepartureDayOffset
        {
            get
            {
                return this.operationalDepartureDayOffsetField;
            }
            set
            {
                this.operationalDepartureDayOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationalDepartureDayOffsetSpecified
        {
            get
            {
                return this.operationalDepartureDayOffsetFieldSpecified;
            }
            set
            {
                this.operationalDepartureDayOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string operationalWaitDuration
        {
            get
            {
                return this.operationalWaitDurationField;
            }
            set
            {
                this.operationalWaitDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string operationalStopDuration
        {
            get
            {
                return this.operationalStopDurationField;
            }
            set
            {
                this.operationalStopDurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class AttributeKey
    {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class Attribute
    {
        
        private AttributeKey attributeKeyField;
        
        private AttributeAttributeValue attributeValueField;
        
        /// <remarks/>
        public AttributeKey attributeKey
        {
            get
            {
                return this.attributeKeyField;
            }
            set
            {
                this.attributeKeyField = value;
            }
        }
        
        /// <remarks/>
        public AttributeAttributeValue attributeValue
        {
            get
            {
                return this.attributeValueField;
            }
            set
            {
                this.attributeValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class AttributeAttributeValue
    {
        
        private string stringValueField;
        
        private int numericValueField;
        
        private bool numericValueFieldSpecified;
        
        private bool booleanValueField;
        
        private bool booleanValueFieldSpecified;
        
        private double decimalValueField;
        
        private bool decimalValueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string stringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int numericValue
        {
            get
            {
                return this.numericValueField;
            }
            set
            {
                this.numericValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numericValueSpecified
        {
            get
            {
                return this.numericValueFieldSpecified;
            }
            set
            {
                this.numericValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool booleanValue
        {
            get
            {
                return this.booleanValueField;
            }
            set
            {
                this.booleanValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool booleanValueSpecified
        {
            get
            {
                return this.booleanValueFieldSpecified;
            }
            set
            {
                this.booleanValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double decimalValue
        {
            get
            {
                return this.decimalValueField;
            }
            set
            {
                this.decimalValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool decimalValueSpecified
        {
            get
            {
                return this.decimalValueFieldSpecified;
            }
            set
            {
                this.decimalValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class VehicleType
    {
        
        private string vehicleTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string vehicleType
        {
            get
            {
                return this.vehicleTypeField;
            }
            set
            {
                this.vehicleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class FormationRestriction
    {
        
        private VehicleType[] vehicleTypesField;
        
        private int maximumLengthField;
        
        private bool maximumLengthFieldSpecified;
        
        private int maximumWeightField;
        
        private bool maximumWeightFieldSpecified;
        
        private int minimumMaxSpeedField;
        
        private bool minimumMaxSpeedFieldSpecified;
        
        private int numberOfWaggonsField;
        
        private bool numberOfWaggonsFieldSpecified;
        
        private bool isDefaultField;
        
        private bool isDefaultFieldSpecified;
        
        private bool emergencyBrakeOverrideField;
        
        private bool emergencyBrakeOverrideFieldSpecified;
        
        private string etcsLevelField;
        
        private bool lzbField;
        
        private bool lzbFieldSpecified;
        
        private string brakingSystemField;
        
        private string tiltingTrainConfField;
        
        private string minBrakingPercentField;
        
        private string lineCategoryField;
        
        private Attribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("vehicleType", IsNullable=false)]
        public VehicleType[] vehicleTypes
        {
            get
            {
                return this.vehicleTypesField;
            }
            set
            {
                this.vehicleTypesField = value;
            }
        }
        
        /// <remarks/>
        public int maximumLength
        {
            get
            {
                return this.maximumLengthField;
            }
            set
            {
                this.maximumLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumLengthSpecified
        {
            get
            {
                return this.maximumLengthFieldSpecified;
            }
            set
            {
                this.maximumLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int maximumWeight
        {
            get
            {
                return this.maximumWeightField;
            }
            set
            {
                this.maximumWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumWeightSpecified
        {
            get
            {
                return this.maximumWeightFieldSpecified;
            }
            set
            {
                this.maximumWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int minimumMaxSpeed
        {
            get
            {
                return this.minimumMaxSpeedField;
            }
            set
            {
                this.minimumMaxSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minimumMaxSpeedSpecified
        {
            get
            {
                return this.minimumMaxSpeedFieldSpecified;
            }
            set
            {
                this.minimumMaxSpeedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int numberOfWaggons
        {
            get
            {
                return this.numberOfWaggonsField;
            }
            set
            {
                this.numberOfWaggonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberOfWaggonsSpecified
        {
            get
            {
                return this.numberOfWaggonsFieldSpecified;
            }
            set
            {
                this.numberOfWaggonsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isDefault
        {
            get
            {
                return this.isDefaultField;
            }
            set
            {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isDefaultSpecified
        {
            get
            {
                return this.isDefaultFieldSpecified;
            }
            set
            {
                this.isDefaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool emergencyBrakeOverride
        {
            get
            {
                return this.emergencyBrakeOverrideField;
            }
            set
            {
                this.emergencyBrakeOverrideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emergencyBrakeOverrideSpecified
        {
            get
            {
                return this.emergencyBrakeOverrideFieldSpecified;
            }
            set
            {
                this.emergencyBrakeOverrideFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string etcsLevel
        {
            get
            {
                return this.etcsLevelField;
            }
            set
            {
                this.etcsLevelField = value;
            }
        }
        
        /// <remarks/>
        public bool lzb
        {
            get
            {
                return this.lzbField;
            }
            set
            {
                this.lzbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lzbSpecified
        {
            get
            {
                return this.lzbFieldSpecified;
            }
            set
            {
                this.lzbFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string brakingSystem
        {
            get
            {
                return this.brakingSystemField;
            }
            set
            {
                this.brakingSystemField = value;
            }
        }
        
        /// <remarks/>
        public string tiltingTrainConf
        {
            get
            {
                return this.tiltingTrainConfField;
            }
            set
            {
                this.tiltingTrainConfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string minBrakingPercent
        {
            get
            {
                return this.minBrakingPercentField;
            }
            set
            {
                this.minBrakingPercentField = value;
            }
        }
        
        /// <remarks/>
        public string lineCategory
        {
            get
            {
                return this.lineCategoryField;
            }
            set
            {
                this.lineCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
        public Attribute[] attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class ItinerarySegmentAttributes
    {
        
        private string trainNumberField;
        
        private string replacementTrainNumberField;
        
        private string[] commercialTrainNamesField;
        
        private string trainProductField;
        
        private FormationRestriction[] formationRestrictionsField;
        
        private string costCenterField;
        
        private Attribute[] attributesField;
        
        /// <remarks/>
        public string trainNumber
        {
            get
            {
                return this.trainNumberField;
            }
            set
            {
                this.trainNumberField = value;
            }
        }
        
        /// <remarks/>
        public string replacementTrainNumber
        {
            get
            {
                return this.replacementTrainNumberField;
            }
            set
            {
                this.replacementTrainNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("commercialTrainName", IsNullable=false)]
        public string[] commercialTrainNames
        {
            get
            {
                return this.commercialTrainNamesField;
            }
            set
            {
                this.commercialTrainNamesField = value;
            }
        }
        
        /// <remarks/>
        public string trainProduct
        {
            get
            {
                return this.trainProductField;
            }
            set
            {
                this.trainProductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("formationRestriction", IsNullable=false)]
        public FormationRestriction[] formationRestrictions
        {
            get
            {
                return this.formationRestrictionsField;
            }
            set
            {
                this.formationRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public string costCenter
        {
            get
            {
                return this.costCenterField;
            }
            set
            {
                this.costCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
        public Attribute[] attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathStop
    {
        
        private ItinerarySegmentAttributes itinerarySegmentAttributesField;
        
        private string[] stoppingReasonsField;
        
        private Times timesField;
        
        private string arrivalTrackField;
        
        private string departureTrackField;
        
        private string linkToNextStopDescriptionField;
        
        private TrainPathStopStopPoint stopPointField;
        
        private bool runningField;
        
        private bool runningFieldSpecified;
        
        /// <remarks/>
        public ItinerarySegmentAttributes itinerarySegmentAttributes
        {
            get
            {
                return this.itinerarySegmentAttributesField;
            }
            set
            {
                this.itinerarySegmentAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("stoppingReason", IsNullable=false)]
        public string[] stoppingReasons
        {
            get
            {
                return this.stoppingReasonsField;
            }
            set
            {
                this.stoppingReasonsField = value;
            }
        }
        
        /// <remarks/>
        public Times times
        {
            get
            {
                return this.timesField;
            }
            set
            {
                this.timesField = value;
            }
        }
        
        /// <remarks/>
        public string arrivalTrack
        {
            get
            {
                return this.arrivalTrackField;
            }
            set
            {
                this.arrivalTrackField = value;
            }
        }
        
        /// <remarks/>
        public string departureTrack
        {
            get
            {
                return this.departureTrackField;
            }
            set
            {
                this.departureTrackField = value;
            }
        }
        
        /// <remarks/>
        public string linkToNextStopDescription
        {
            get
            {
                return this.linkToNextStopDescriptionField;
            }
            set
            {
                this.linkToNextStopDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public TrainPathStopStopPoint stopPoint
        {
            get
            {
                return this.stopPointField;
            }
            set
            {
                this.stopPointField = value;
            }
        }
        
        /// <remarks/>
        public bool running
        {
            get
            {
                return this.runningField;
            }
            set
            {
                this.runningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool runningSpecified
        {
            get
            {
                return this.runningFieldSpecified;
            }
            set
            {
                this.runningFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathStopStopPoint
    {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathVariant
    {
        
        private DateInterval[] validityField;
        
        private string trainDescriptionField;
        
        private string routeNumberField;
        
        private string stateField;
        
        private string createdUserIdField;
        
        private string orderingTransportationCompanyField;
        
        private TrainPathStop[] trainPathItineraryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("validitySegment", IsNullable=false)]
        public DateInterval[] validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
        
        /// <remarks/>
        public string trainDescription
        {
            get
            {
                return this.trainDescriptionField;
            }
            set
            {
                this.trainDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string routeNumber
        {
            get
            {
                return this.routeNumberField;
            }
            set
            {
                this.routeNumberField = value;
            }
        }
        
        /// <remarks/>
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string createdUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string orderingTransportationCompany
        {
            get
            {
                return this.orderingTransportationCompanyField;
            }
            set
            {
                this.orderingTransportationCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trainPathStop", IsNullable=false)]
        public TrainPathStop[] trainPathItinerary
        {
            get
            {
                return this.trainPathItineraryField;
            }
            set
            {
                this.trainPathItineraryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathKey
    {
        
        private string infrastructureManagerField;
        
        private string trainPathIdField;
        
        private TrainPathKeyTimetableVersion timetableVersionField;
        
        /// <remarks/>
        public string infrastructureManager
        {
            get
            {
                return this.infrastructureManagerField;
            }
            set
            {
                this.infrastructureManagerField = value;
            }
        }
        
        /// <remarks/>
        public string trainPathId
        {
            get
            {
                return this.trainPathIdField;
            }
            set
            {
                this.trainPathIdField = value;
            }
        }
        
        /// <remarks/>
        public TrainPathKeyTimetableVersion timetableVersion
        {
            get
            {
                return this.timetableVersionField;
            }
            set
            {
                this.timetableVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathKeyTimetableVersion
    {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPath
    {
        
        private TrainPathKey trainPathKeyField;
        
        private string infrastructureManagerTrainPathIdField;
        
        private DateInterval[] importValidityFrameField;
        
        private TrainPathVariant[] trainPathVariantsField;
        
        /// <remarks/>
        public TrainPathKey trainPathKey
        {
            get
            {
                return this.trainPathKeyField;
            }
            set
            {
                this.trainPathKeyField = value;
            }
        }
        
        /// <remarks/>
        public string infrastructureManagerTrainPathId
        {
            get
            {
                return this.infrastructureManagerTrainPathIdField;
            }
            set
            {
                this.infrastructureManagerTrainPathIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("validitySegment", IsNullable=false)]
        public DateInterval[] importValidityFrame
        {
            get
            {
                return this.importValidityFrameField;
            }
            set
            {
                this.importValidityFrameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trainPathVariant", IsNullable=false)]
        public TrainPathVariant[] trainPathVariants
        {
            get
            {
                return this.trainPathVariantsField;
            }
            set
            {
                this.trainPathVariantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote")]
    public partial class TrainPathImportRequest
    {
        
        private string importProfileField;
        
        private TrainPath[] trainPathsField;
        
        private NetworkPointKey[] stopPointsField;
        
        private TimetableVersion[] timetableVersionsField;
        
        /// <remarks/>
        public string importProfile
        {
            get
            {
                return this.importProfileField;
            }
            set
            {
                this.importProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trainPath", IsNullable=false)]
        public TrainPath[] trainPaths
        {
            get
            {
                return this.trainPathsField;
            }
            set
            {
                this.trainPathsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("stopPoint", IsNullable=false)]
        public NetworkPointKey[] stopPoints
        {
            get
            {
                return this.stopPointsField;
            }
            set
            {
                this.stopPointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("timetableVersion", IsNullable=false)]
        public TimetableVersion[] timetableVersions
        {
            get
            {
                return this.timetableVersionsField;
            }
            set
            {
                this.timetableVersionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote", ConfigurationName="TrainPathImportService.TrainPathImportWebFacade")]
    internal interface TrainPathImportWebFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/mb/intf/trainpath/standard/remote", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrainPathImportService.TechnicalFaultResponse), Action="http://www.ivu.de/mb/intf/trainpath/standard/remote", Name="technicalFaultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainPathImportService.importTrainPathsResponse> importTrainPathsAsync(TrainPathImportService.importTrainPaths request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class importTrainPaths
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote", Order=0)]
        public TrainPathImportService.TrainPathImportRequest trainPathImportRequest;
        
        public importTrainPaths()
        {
        }
        
        public importTrainPaths(TrainPathImportService.TrainPathImportRequest trainPathImportRequest)
        {
            this.trainPathImportRequest = trainPathImportRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class importTrainPathsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/mb/intf/trainpath/standard/remote", Order=0)]
        public TrainPathImportService.TrainPathImportResponse trainPathImportResponse;
        
        public importTrainPathsResponse()
        {
        }
        
        public importTrainPathsResponse(TrainPathImportService.TrainPathImportResponse trainPathImportResponse)
        {
            this.trainPathImportResponse = trainPathImportResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface TrainPathImportWebFacadeChannel : TrainPathImportService.TrainPathImportWebFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class TrainPathImportWebFacadeClient : System.ServiceModel.ClientBase<TrainPathImportService.TrainPathImportWebFacade>, TrainPathImportService.TrainPathImportWebFacade
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TrainPathImportWebFacadeClient() : 
                base(TrainPathImportWebFacadeClient.GetDefaultBinding(), TrainPathImportWebFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TrainPathImportWebFacadeBeanPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainPathImportWebFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(TrainPathImportWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), TrainPathImportWebFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainPathImportWebFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TrainPathImportWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainPathImportWebFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TrainPathImportWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainPathImportWebFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainPathImportService.importTrainPathsResponse> TrainPathImportService.TrainPathImportWebFacade.importTrainPathsAsync(TrainPathImportService.importTrainPaths request)
        {
            return base.Channel.importTrainPathsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainPathImportService.importTrainPathsResponse> importTrainPathsAsync(TrainPathImportService.TrainPathImportRequest trainPathImportRequest)
        {
            TrainPathImportService.importTrainPaths inValue = new TrainPathImportService.importTrainPaths();
            inValue.trainPathImportRequest = trainPathImportRequest;
            return ((TrainPathImportService.TrainPathImportWebFacade)(this)).importTrainPathsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TrainPathImportWebFacadeBeanPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TrainPathImportWebFacadeBeanPort))
            {
                return new System.ServiceModel.EndpointAddress("http://bnb18327.ivu-ag.com:20000/intf.trainpath.standardimport.impl/TrainPathImpo" +
                        "rtWebFacadeBean");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TrainPathImportWebFacadeClient.GetBindingForEndpoint(EndpointConfiguration.TrainPathImportWebFacadeBeanPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TrainPathImportWebFacadeClient.GetEndpointAddress(EndpointConfiguration.TrainPathImportWebFacadeBeanPort);
        }
        
        public enum EndpointConfiguration
        {
            
            TrainPathImportWebFacadeBeanPort,
        }
    }
}
